services:
  keynote-db:
    image: postgres:15-alpine
    container_name: keynote-db
    environment:
      POSTGRES_DB: keynote_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - keynote-data:/var/lib/postgresql/data
    networks:
      - conferix-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  conference-db:
    image: postgres:15-alpine
    container_name: conference-db
    environment:
      POSTGRES_DB: conference_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - conference-data:/var/lib/postgresql/data
    networks:
      - conferix-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-db:
    image: postgres:15-alpine
    container_name: conferix-keycloak-db
    environment:
      POSTGRES_DB: conferix_keycloak_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "5434:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - conferix-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-conferix
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@conferix.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - conferix-network
    depends_on:
      - keynote-db
      - conference-db
      - keycloak-db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak-conferix
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://conferix-keycloak-db:5432/conferix_keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_PORT: 8080
    ports:
      - "8090:8080"
    #    volumes:
    #      - ./api-gateway/themes:/opt/keycloak/themes
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - conferix-network
networks:
  conferix-network:
    driver: bridge
volumes:
  keycloak-data:
  keynote-data:
  conference-data:
