services:
  keynot-db:
    image: postgres:15-alpine
    container_name: company-db
    profiles: [ "default", "all" ]
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - company-data:/var/lib/postgresql/data
    networks:
      - inovSmart-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aliyara29" ]
      interval: 10s
      timeout: 5s
      retries: 5